### ISSUE TITLE
Socket disconnection causing service to stop

### ISSUE THREAD

**Issue by ruuk** [elbowz/xbmc.service.pushbullet#13]
```
02:18:22 T:1838354280   ERROR: [Pushbullet]:
02:18:22 T:1838354280   ERROR: No handlers could be found for logger "root"
02:18:22 T:1826903144   ERROR: /storage/sdcard0/Android/data/org.xbmc.xbmc/files/.xbmc/addons/service.pushbullet/lib/external/websocket/_core.py:837: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
                                              message = getattr(e, 'strerror', getattr(e, 'message', ''))
02:18:22 T:1826903144   ERROR: Exception in thread Thread-3:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/XBMC-Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/threading.py", line 532, in __bootstrap_inner
                                              File "/home/jenkins/workspace/XBMC-Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/threading.py", line 484, in run
                                              File "/storage/sdcard0/Android/data/org.xbmc.xbmc/files/.xbmc/addons/service.pushbullet/lib/external/websocket/_app.py", line 108, in _send_ping
                                                self.sock.ping()
                                              File "/storage/sdcard0/Android/data/org.xbmc.xbmc/files/.xbmc/addons/service.pushbullet/lib/external/websocket/_core.py", line 645, in ping
                                                self.send(payload, ABNF.OPCODE_PING)
                                              File "/storage/sdcard0/Android/data/org.xbmc.xbmc/files/.xbmc/addons/service.pushbullet/lib/external/websocket/_core.py", line 602, in send
                                                return self.send_frame(frame)
                                              File "/storage/sdcard0/Android/data/org.xbmc.xbmc/files/.xbmc/addons/service.pushbullet/lib/external/websocket/_core.py", line 628, in send_frame
                                                l = self._send(data)
                                              File "/storage/sdcard0/Android/data/org.xbmc.xbmc/files/.xbmc/addons/service.pushbullet/lib/external/websocket/_core.py", line 832, in _send
                                                return self.sock.send(data)
                                              File "/home/jenkins/workspace/XBMC-Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/ssl.py", line 94, in <lambda>
                                              File "/home/jenkins/workspace/XBMC-Android-ARM/tools/depends/xbmc-depends/arm-linux-androideabi-android-14/lib/python2.6/ssl.py", line 174, in send
                                            error: [Errno 104] Connection reset by peer
02:18:22 T:1838354280   DEBUG: [Pushbullet]: Socket closed
```

**Comment by elbowz** [comment]
When, what...why?

How can I reproduce it?

When I had tried, on disconnection the service retried to connect every **try_reconnect** seconds (on windows)

**Comment by ruuk** [comment]
I've still got to look closer at this. It happens on my Ouya. If it's been on for a few days it will eventually disconnect with this error. Looking at the error, this seems to be related to a ping error, and perhaps there is something different there. I haven't looked into it yet at all, I've just had this happen a couple of times, so I created the issue to save the log snippet and remind me to check it closer.

**Comment by elbowz** [comment]
What say your Ouya? :)

**Comment by ruuk** [comment]
Things are working well now. It reconnects on any disconnects. I'll close it.
